// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class NativeImageError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "NativeImageError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? NativeImageError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum NativeImageApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


private class NativeImageApiPigeonCodecReader: FlutterStandardReader {
}

private class NativeImageApiPigeonCodecWriter: FlutterStandardWriter {
}

private class NativeImageApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NativeImageApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NativeImageApiPigeonCodecWriter(data: data)
  }
}

class NativeImageApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = NativeImageApiPigeonCodec(readerWriter: NativeImageApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NativeImageHostApi {
  /// Decodes the asset to a premultiplied RGBA8888 buffer allocated with
  /// `malloc`. The shorter side of the result is [width]/[height] (aspect
  /// fill). Returns `{pointer, width, height, rowBytes}`, or `null` when the
  /// request was cancelled before a buffer was allocated.
  ///
  /// Once a buffer is allocated the host always replies with it, even if a
  /// cancel arrived meanwhile: the Dart side owns the buffer and frees it.
  ///
  /// Errors use the codes `not_found`, `icloud_not_downloaded`, and
  /// `decode_failed`.
  func requestImage(assetId: String, requestId: Int64, width: Int64, height: Int64, isVideo: Bool, allowNetwork: Bool, completion: @escaping (Result<[String: Int64]?, Error>) -> Void)
  /// Stops [requestId] if it has not allocated a buffer yet. A cancel that
  /// arrives before its request is remembered and applied when it does.
  func cancelRequest(requestId: Int64) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NativeImageHostApiSetup {
  static var codec: FlutterStandardMessageCodec { NativeImageApiPigeonCodec.shared }
  /// Sets up an instance of `NativeImageHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NativeImageHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Decodes the asset to a premultiplied RGBA8888 buffer allocated with
    /// `malloc`. The shorter side of the result is [width]/[height] (aspect
    /// fill). Returns `{pointer, width, height, rowBytes}`, or `null` when the
    /// request was cancelled before a buffer was allocated.
    ///
    /// Once a buffer is allocated the host always replies with it, even if a
    /// cancel arrived meanwhile: the Dart side owns the buffer and frees it.
    ///
    /// Errors use the codes `not_found`, `icloud_not_downloaded`, and
    /// `decode_failed`.
    let requestImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.photo_manager_native_image.NativeImageHostApi.requestImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let assetIdArg = args[0] as! String
        let requestIdArg = args[1] as! Int64
        let widthArg = args[2] as! Int64
        let heightArg = args[3] as! Int64
        let isVideoArg = args[4] as! Bool
        let allowNetworkArg = args[5] as! Bool
        api.requestImage(assetId: assetIdArg, requestId: requestIdArg, width: widthArg, height: heightArg, isVideo: isVideoArg, allowNetwork: allowNetworkArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestImageChannel.setMessageHandler(nil)
    }
    /// Stops [requestId] if it has not allocated a buffer yet. A cancel that
    /// arrives before its request is remembered and applied when it does.
    let cancelRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.photo_manager_native_image.NativeImageHostApi.cancelRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! Int64
        do {
          try api.cancelRequest(requestId: requestIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelRequestChannel.setMessageHandler(nil)
    }
  }
}
