// Autogenerated from Pigeon (v27.3.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.fluttercandies.photo_manager_native_image

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object NativeImageApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is NativeImageError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class NativeImageError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()
private open class NativeImageApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return     super.readValueOfType(type, buffer)
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    super.writeValue(stream, value)
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NativeImageHostApi {
  /**
   * Decodes the asset to a premultiplied RGBA8888 buffer allocated with
   * `malloc`. The shorter side of the result is [width]/[height] (aspect
   * fill). Returns `{pointer, width, height, rowBytes}`, or `null` when the
   * request was cancelled before a buffer was allocated.
   *
   * Once a buffer is allocated the host always replies with it, even if a
   * cancel arrived meanwhile: the Dart side owns the buffer and frees it.
   *
   * Errors use the codes `not_found`, `icloud_not_downloaded`, and
   * `decode_failed`.
   */
  fun requestImage(assetId: String, requestId: Long, width: Long, height: Long, isVideo: Boolean, allowNetwork: Boolean, callback: (Result<Map<String, Long>?>) -> Unit)
  /**
   * Stops [requestId] if it has not allocated a buffer yet. A cancel that
   * arrives before its request is remembered and applied when it does.
   */
  fun cancelRequest(requestId: Long)

  companion object {
    /** The codec used by NativeImageHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeImageApiPigeonCodec()
    }
    /** Sets up an instance of `NativeImageHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NativeImageHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.photo_manager_native_image.NativeImageHostApi.requestImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val assetIdArg = args[0] as String
            val requestIdArg = args[1] as Long
            val widthArg = args[2] as Long
            val heightArg = args[3] as Long
            val isVideoArg = args[4] as Boolean
            val allowNetworkArg = args[5] as Boolean
            api.requestImage(assetIdArg, requestIdArg, widthArg, heightArg, isVideoArg, allowNetworkArg) { result: Result<Map<String, Long>?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeImageApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NativeImageApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.photo_manager_native_image.NativeImageHostApi.cancelRequest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as Long
            val wrapped: List<Any?> = try {
              api.cancelRequest(requestIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              NativeImageApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
